import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage();
page.on("request", (r) => { if (r.url().includes("ajustes")) console.log("REQ", r.method(), r.url()); });
page.on("requestfailed", (r) => console.log("FAILED", r.url(), r.failure()?.errorText));
await page.addInitScript(() => localStorage.setItem("gerador:jornada-vista", "1"));
await page.goto("http://localhost:8080");
await page.getByRole("button", { name: "Entrar" }).first().click();
await page.getByPlaceholder("voce@empresa.com").fill("dev@gerador.local");
await page.getByRole("button", { name: "Entrar" }).click();
await page.getByRole("button", { name: "time-pagamentos", exact: true }).click();
await page.getByRole("button", { name: "+ Serviço", exact: true }).waitFor({ timeout: 15000 });
const direto = await page.evaluate(async () => {
  const r = await fetch("http://localhost:4000/ajustes", { credentials: "include" });
  return { status: r.status, corpo: (await r.text()).slice(0, 80) };
});
console.log("FETCH DIRETO:", JSON.stringify(direto));
await page.getByRole("button", { name: "⚙ Configurações" }).click();
await page.getByRole("button", { name: /Acessos/ }).click();
await page.waitForTimeout(2500);
console.log("secao:", await page.getByTestId("solicitacoes-de-ajuste").count());
await browser.close();
